### ISSUE TITLE
Download button not working using Firefox/Chrome/Edge

### ISSUE THREAD

**Issue by gh7531** [Thecakeisgit/Dckuino.js#14]
Hello,
as stated in the title the download button isn't working for me. Nothing happens if I click on it.
Since it doesn't do anything besides changing the style of the button if the mouse hovers over it I can't provide screenshots or error messages.

Probably related to #13 

If I remember correctly a few weeks ago it worked fine but I'm not sure about that.

**Comment by Thecakeisgit** [comment]
Okay thanks for your report man ;D @gh7531.
I'll see how i can fix this up.

**Comment by Thecakeisgit** [comment]
It's due to github raw.. I included my js file from it.. @gh7531
