### ISSUE TITLE
Keyboard layout

### ISSUE THREAD

**Issue by KevinDenys** [Thecakeisgit/Dckuino.js#15]
I have an Belgian Dot layout as keyboard. So when I try to write "azerty" using the programmed arduino leonardo it types "qwerty". How Can I fix this?

**Comment by Thecakeisgit** [comment]
Approximately the same thing as #10

**Comment by Thecakeisgit** [comment]
#10

**Comment by Thecakeisgit** [comment]
You can use the **Download Sketch !** button ;D And select **fr_FR** locale, if you got a ~French Belgian keyboard ;D

**Comment by KevinDenys** [comment]
Okay this fixed one of my problems, now I can't get Keyboard.press(KEY_LEFT_GUI); to work?

**Comment by Thecakeisgit** [comment]
KEY_LEFT_GUI is hard coded, so if ut doesn't work, i don't know how you can make it work !
Try to post your entire code please ;D

**Comment by KevinDenys** [comment]
`/*
 * Generated with <3 by Dckuino.js, an open source project !
 */

#include "Keyboard.h"

void typeKey(uint8_t key)
{
  Keyboard.press(key);
  delay(50);
  Keyboard.release(key);
}

/* Init function */
void setup()
{
  // Begining the Keyboard stream
  Keyboard.begin();

  // Wait 500ms
  delay(500);

  delay(750);

  Keyboard.press(KEY_LEFT_GUI);
  Keyboard.press('r');
  Keyboard.releaseAll();

  delay(1000);

  Keyboard.print("cmd");

  typeKey(KEY_RETURN);

  // Ending stream
  Keyboard.end();
}

/* Unused endless loop */
void loop() {}
`

**Comment by Thecakeisgit** [comment]
Hmm kinda weird, i don't know why it doesn't work.. @KevinDenys

**Comment by KevinDenys** [comment]
Hmmmm I just tried running it on my windows 10 and here it opens the cmd. Looks like my windows 7 is being funky. Thanks for fixing the keyboard layout problem! Issue fixed

**Comment by Thecakeisgit** [comment]
You're welcome ! @KevinDenys
