### ISSUE TITLE
A few issues

### ISSUE THREAD

**Issue by d4n5h** [Thecakeisgit/Dckuino.js#3]
@Thecakeisgit 
1. You can't use PHP on GitHub Pages.

2. STRING command has a bug,it adds lead whites-spaces all the time.
Sometimes you need to add a white-space in the beginning of a string, but not all the time.
In my compiler you can do "STRING Without white space" and also "STRING⋅⋅With white space".

3. Look at my updated GUI/Index page. i added Codemirror for syntax highlighting and and i've "updated" the design a bit. 

https://d4n5h.github.io/Duckuino/

**Comment by Thecakeisgit** [comment]
1. Thanks i did'nt know.
2. Ill fix that
3. Cool, it's very good :D

**Comment by d4n5h** [comment]
@Thecakeisgit 
I've reimplemented console debugging like in your compiler...
Now you don't have any excuse for not switching to my compiler :)

**Comment by d4n5h** [comment]
@Thecakeisgit 
I've "Download Payload" button...

**Comment by d4n5h** [comment]
@Thecakeisgit 
You didn't add REPLAY/REPEAT

**Comment by d4n5h** [comment]
"CTRL ALT TEST" Don't work lol

**Comment by Thecakeisgit** [comment]
Yep i know ^^ i'll add id this soon, i added payload dl too
Yes it works ! it throws an error as expected ! ;D

**Comment by d4n5h** [comment]
Sure... if you don't realise that REPEAT is dependant on everything to be in same line, so my solution is better ;)

**Comment by Thecakeisgit** [comment]
Leave me this ;D

**Comment by Thecakeisgit** [comment]
You'll see :D

**Comment by d4n5h** [comment]
@Thecakeisgit 
Issue with REPEAT/REPLAY:
Try doing:
CTRL a
REPEAT 10

**Comment by Thecakeisgit** [comment]
Yes ?

**Comment by d4n5h** [comment]
@Thecakeisgit 
Try:
CRTL ALT a
REPLAY 10

**Comment by d4n5h** [comment]
@Thecakeisgit 
My bad, REPEAT is working great.
Can i use your solution?

**Comment by Thecakeisgit** [comment]
Of course you can do it ! ;D
