### ISSUE TITLE
ALT F2

### ISSUE THREAD

**Issue by d4n5h** [Thecakeisgit/Dckuino.js#4]
I switched to your compiler and reverted back because someone (EchoUnderscoreNine) had an issue:
"console Error: Unknown command or key 'F2' at line: 2. ---> any guesses?
it was running fine til your update an hour ago."

**Comment by d4n5h** [comment]
@Thecakeisgit 
Oh you just need to add F-keys to the array...

**Comment by Thecakeisgit** [comment]
Fixed with ur help :D #5

**Comment by d4n5h** [comment]
You want me to merge my repository with yours? It's basically the same compiler now just a different GUI (mine is better) and download function (yours is better, if you can add it it will be awesome) what do you say?
