### ISSUE TITLE
Your compiler is totally bugged

### ISSUE THREAD

**Issue by d4n5h** [Thecakeisgit/Dckuino.js#7]
1. You added the typeKey utility function in the end of the payload so it will not run...
Fix: Add it to the beginning of the payload/script (before the `void setup(){...};`).

2. You don't have support for PAGEUP/PAGEDOWN.

3. You didn't add `#include <Keyboard.h>` and/or `#include <Mouse.h>` at the beginning of the payload.

As it seems, you probably don't even have a atmega32u4 board to test your script.

I've fixed all of the above in my repository.

**Comment by Thecakeisgit** [comment]
1. Ok Thanks, i'll fix it.
2. I'll add this too
3. Keyboard.h is already included by arduino core, why include it again ? c:

I got a wonderful arduino mini to test this ;D And i worked without the include ^^

**Comment by d4n5h** [comment]
The Arduino (Pro) Mini is a ATmega328 based MCU.
You cannot use the Keyboard.h library with it so there is no way that you've tested it and it worked.

**Comment by Thecakeisgit** [comment]
Sorry it was an Arduino Micro ;D

**Comment by d4n5h** [comment]
Also, you would get a error because of the typeKey() function.

**Comment by Thecakeisgit** [comment]
Nope, i tested ^^ No error.
With this:
```c
/*
 * Generated with <3 by Dckuino.js, an open source project !
 */

// Init function
void setup()
{
  // Begining the stream
  Keyboard.begin();

  // Waiting 500ms for init
  delay(500);

  typeKey(108);

  Keyboard.print("My name is");
}

void typeKey(int key)
{
  Keyboard.press(key);
  delay(50);
  Keyboard.release(key);
}

// Unused
void loop() {}
```

**Comment by d4n5h** [comment]
It outputs an error.

You didn't even check it.

**Comment by d4n5h** [comment]
```
Arduino: 1.6.11 (Windows 10), Board: "Arduino/Genuino Micro"

WARNING: Category '' in library UIPEthernet is not valid. Setting to 'Uncategorized'
C:\Users\Daniel\Documents\Arduino\sketch_oct18c\sketch_oct18c.ino: In function 'void setup()':

sketch_oct18c:9: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?
   Keyboard.begin();

   ^

C:\Users\Daniel\Documents\Arduino\sketch_oct18c\sketch_oct18c.ino: In function 'void typeKey(int)':

sketch_oct18c:21: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?
   Keyboard.press(key);

   ^

exit status 1
'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by d4n5h** [comment]
Again, you just bullshiting.... 
Just fix you shit....

**Comment by Thecakeisgit** [comment]
Yes i'll fix it tomorrow, i've tested, but on linux, so i don't know what can change but i did'nt got any error *-*

**Comment by d4n5h** [comment]
I've tested it on macOS and on Windows 10 and it's totally bugged...

**Comment by Thecakeisgit** [comment]
Ok i'll fix i said, don't get angry..

**Comment by Thecakeisgit** [comment]
When i add #include <Keyboard.h>, this happens : 
sketch_oct19a.ino:5:22: fatal error: Keyboard.h: No such file or directory
compilation terminated.

**Comment by Thecakeisgit** [comment]
What's your arduino ide version ? Mine is 2:1.0.5+dfsg2-4

**Comment by d4n5h** [comment]
It's in the error report - Arduino: 1.6.11

**Comment by d4n5h** [comment]
I know what is the problem. You probably didn't set the MCU type to Arduino/Genuino Micro.
It's in Tools->Board.

**Comment by Thecakeisgit** [comment]
It was set to Arduino Micro, and i compiled, without uploading and it did this error.. Kinda weird.

**Comment by Thecakeisgit** [comment]
When i use Keyboard object, without including, this works.. \*-\*

**Comment by Thecakeisgit** [comment]
My bad, i updated my arduino ide version and it works..

**Comment by d4n5h** [comment]
Maybe we should add a note at the README file that indicates that the IDE must be updated to the latest version so there will be no cross-platform compatibility issues.

**Comment by Thecakeisgit** [comment]
Yep ^^ it was a problem in Ubuntu repository, there is only arduino 2:1.0.5

**Comment by Thecakeisgit** [comment]
[a7330f6](https://github.com/Thecakeisgit/Dckuino.js/commit/a7330f65e555fa80d547b88961cee64c65dbd79c) resolved it.
