### ISSUE TITLE
Suggestion regarding our projects (Not a Issue)

### ISSUE THREAD

**Issue by d4n5h** [Thecakeisgit/Dckuino.js#9]
@Thecakeisgit 
In order to make the mouse emulation be absolute (not relative) regarding screen resolution,
I've switched from the Arduino HID library to this library: https://github.com/NicoHood/HID
That means there will be a dependency in order to use my compiler.
I'm suggesting that you'll keep using the standard Arduino HID library on your compiler to give people the option to use it easily if they don't want to use the mouse emulation.
I've referenced your repository in my documentation and i suggest you'll reference mine in your documentation ("If you need to perform mouse emulation then use d4n5h's Duckuino").
I think that it's good idea.
By the way, what about the updates you've said you'll make (embedded console log and payload library)?

**Comment by Thecakeisgit** [comment]
Ok wait a min ^^
My updates are "In a good way", i'm gently working on it :D
